### ISSUE TITLE
Breaks in workers

### ISSUE THREAD

**Issue by ahutchings** [AmpersandJS/ampersand-version#2]
ampersand-version has a hard dependency on `window`, which doesn't exist in web workers and throws `Uncaught ReferenceError: window is not defined`.

I confirmed that ampersand-state functions in a worker if `window` is changed to `global` in ampersand-version. Browserify will resolve `global` to the appropriate context in both browser windows and workers.

**Comment by latentflip** [comment]
Ooft, good spot, my bad. I think I'll change this to only export version info if window exists, as that probably makes more sense.

**Comment by latentflip** [comment]
Okay, published as 1.0.2

You'll need to either reinstall your node modules to pick it up in all the sub dependencies, or install `"ampersand-version": "^1.0.2"` at the top level of your app.

**Comment by ahutchings** [comment]
Great, thanks!
